### ISSUE TITLE
For now this is just showing the .bash_history file. I want the user to enter commands in a session and show the commands entered during the session.

### ISSUE THREAD

**Issue by roh-7** [roh-7/OS#1]

**Comment by a7r3** [comment]
Maybe this gist I just created can help


https://gist.github.com/a7r3/67f1ab63727c1ab6386250ec63acd733

**To get started, enter `bash someshell.sh` - A prompt would appear**  

* **This is an Imitation of a shell**, which can accept and exec a command, as well as get it saved in a `history_file`  
* When user enters `historypls`, the script would show the contents of `history_file`  
* To exit the script, user has to issue the Key Combo "Ctrl+C" (Interrupt Signal)  

**Limitations:**

* You can't scroll left/right between characters  
* You can't scroll through command history with up/down keys.
   - `historypls` does the task for now

This can be improved if you like it
Provide your Inputs on the concept, here's how it looks like (It does your task)

![screenshot_20171015_161119](https://user-images.githubusercontent.com/14874906/31584029-8e94130c-b1c3-11e7-9547-7ee8476d7a54.png)

**Comment by roh-7** [comment]
Woah! thanks a ton @a7r3
